### ISSUE TITLE
Resource files are missing

### ISSUE THREAD

**Issue by snj33v** [johnflynnjohnflynn/BalanceSPTeufelsbergReverb#2]
without resources, projucer doesn't exports build system nor it builds

**Comment by johnflynnjohnflynn** [comment]
Hi Sanjeev, thanks for getting in touch. Unfortunately we are not allowed to make the graphics resources open source, so they are not included. But you can easily add any .png files renamed to the required names into a 'Resources' folder and it should build. Or if you look at FalkTX's fork https://github.com/falkTX/BalanceSPTeufelsbergReverb he has added zero-sized resources to get it to build.
